apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-operator-spark
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-operator-spark-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-operator-spark-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: spark-operator-spark
  namespace: default
roleRef:
  kind: Role
  name: spark-operator-spark-role
  apiGroup: rbac.authorization.k8s.io