apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "superset.name" . }}-config
  labels:
    {{ include "superset.labels" . | nindent 4 }}
data:
  superset_config.py: |
    import os

    APP_NAME = "Apache Superset"

    SECRET_KEY = os.environ.get('SUPERSET_SECRET_KEY', 'your_secret_key_here')

    TALISMAN_ENABLED = True
    TALISMAN_CONFIG = {
        'content_security_policy': {
            'default-src': ["'self'"],
            'script-src': ["'self'", "'unsafe-inline'"],
            'style-src': ["'self'", "'unsafe-inline'"],
        },
        'force_https': False,
        'force_https_permanent': False
    }

    # SQLAlchemy database URI
    {{- if .Values.superset.env.database.host }}
    SQLALCHEMY_DATABASE_URI = os.environ.get('SUPERSET_DATABASE_URI')
    {{- else }}
    SQLALCHEMY_DATABASE_URI = 'sqlite:////app/superset_home/superset.db'
    {{- end }}

    WTF_CSRF_ENABLED = True
    WTF_CSRF_TIME_LIMIT = None

    MAPBOX_API_KEY = os.environ.get('MAPBOX_API_KEY', '')

    {{- if .Values.superset.env.redis.enabled }}
    # Redis configuration
    REDIS_HOST = os.environ.get('REDIS_HOST', 'redis')
    REDIS_PORT = os.environ.get('REDIS_PORT', '6379')
    REDIS_PASSWORD = os.environ.get('REDIS_PASSWORD', 'redispassword')

    # Cache configuration
    CACHE_CONFIG = {
        'CACHE_TYPE': 'RedisCache',
        'CACHE_DEFAULT_TIMEOUT': 300,
        'CACHE_KEY_PREFIX': 'superset_',
        'CACHE_REDIS_HOST': REDIS_HOST,
        'CACHE_REDIS_PORT': REDIS_PORT,
        'CACHE_REDIS_PASSWORD': REDIS_PASSWORD,
        'CACHE_REDIS_DB': 0,
    }

    DATA_CACHE_CONFIG = {
        'CACHE_TYPE': 'RedisCache',
        'CACHE_DEFAULT_TIMEOUT': 86400,  # 24 hours
        'CACHE_KEY_PREFIX': 'superset_data_',
        'CACHE_REDIS_HOST': REDIS_HOST,
        'CACHE_REDIS_PORT': REDIS_PORT,
        'CACHE_REDIS_PASSWORD': REDIS_PASSWORD,
        'CACHE_REDIS_DB': 1,
    }

    FILTER_STATE_CACHE_CONFIG = {
        'CACHE_TYPE': 'RedisCache',
        'CACHE_DEFAULT_TIMEOUT': 86400,
        'CACHE_KEY_PREFIX': 'superset_filter_',
        'CACHE_REDIS_HOST': REDIS_HOST,
        'CACHE_REDIS_PORT': REDIS_PORT,
        'CACHE_REDIS_PASSWORD': REDIS_PASSWORD,
        'CACHE_REDIS_DB': 2,
    }

    EXPLORE_FORM_DATA_CACHE_CONFIG = {
        'CACHE_TYPE': 'RedisCache',
        'CACHE_DEFAULT_TIMEOUT': 86400,
        'CACHE_KEY_PREFIX': 'superset_explore_',
        'CACHE_REDIS_HOST': REDIS_HOST,
        'CACHE_REDIS_PORT': REDIS_PORT,
        'CACHE_REDIS_PASSWORD': REDIS_PASSWORD,
        'CACHE_REDIS_DB': 3,
    }
    {{- end }}

    SUPERSET_WEBSERVER_PORT = 8088
    SUPERSET_WEBSERVER_TIMEOUT = 120

    FEATURE_FLAGS = {
        "ENABLE_TEMPLATE_PROCESSING": True,
        "DASHBOARD_NATIVE_FILTERS": True,
        "DASHBOARD_CROSS_FILTERS": True,
        "DASHBOARD_NATIVE_FILTERS_SET": True,
        "DASHBOARD_CACHE": True,
    }

    ROW_LIMIT = 50000

    SUPERSET_WEBSERVER_TIMEOUT = 300
    SQLLAB_TIMEOUT = 300

    ENABLE_CORS = True
    CORS_OPTIONS = {
        'supports_credentials': True,
        'allow_headers': ['*'],
        'resources': ['*'],
        'origins': ['*']
    }

    {{- if .Values.superset.env.clickhouse.enabled }}
    CLICKHOUSE_HOST = "{{ .Values.superset.env.clickhouse.host }}"
    CLICKHOUSE_PORT = "{{ .Values.superset.env.clickhouse.port }}"
    CLICKHOUSE_DATABASE = "{{ .Values.superset.env.clickhouse.database }}"
    CLICKHOUSE_USER = "{{ .Values.superset.env.clickhouse.username }}"
    CLICKHOUSE_PASSWORD = "{{ .Values.superset.env.clickhouse.password }}"
    CLICKHOUSE_PROTOCOL = "{{ .Values.superset.env.clickhouse.protocol }}"

    CLICKHOUSE_URI = f"clickhousedb://{CLICKHOUSE_USER}:{CLICKHOUSE_PASSWORD}@{CLICKHOUSE_HOST}:{CLICKHOUSE_PORT}/{CLICKHOUSE_DATABASE}"
    {{- end }}