apiVersion: v1
kind: Service
metadata:
  name: {{ include "superset.name" . }}
  labels:
    {{ include "superset.labels" . | nindent 4 }}
spec:
  type: {{ .Values.superset.service.type }}
  ports:
  - port: {{ .Values.superset.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{ include "superset.selectorLabels" . | nindent 4 }}