apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trino.name" . }}-coordinator
  labels:
    {{ include "trino.labels" . | nindent 4 }}
    component: coordinator
spec:
  replicas: {{ .Values.trino.coordinator.replicas }}
  selector:
    matchLabels:
      {{ include "trino.selectorLabels" . | nindent 6 }}
      component: coordinator
  template:
    metadata:
      labels:
        {{ include "trino.selectorLabels" . | nindent 8 }}
        component: coordinator
    spec:
      initContainers:
        - name: wait-for-hdfs
          image: busybox:1.35
          command: ['sh', '-c']
          args:
            - |
              echo "Waiting for HDFS NameNode..."
              until nc -z {{ .Values.trino.hdfs.namenode.host }} {{ .Values.trino.hdfs.namenode.rpcPort }}; do
                echo "HDFS NameNode not ready, waiting..."
                sleep 5
              done
              echo "HDFS NameNode is ready!"
      containers:
      - name: coordinator
        image: "{{ .Values.trino.coordinator.image.repository }}:{{ .Values.trino.coordinator.image.tag }}"
        imagePullPolicy: {{ .Values.trino.coordinator.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: POD_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        volumeMounts:
        - name: config
          mountPath: /etc/trino
        - name: catalog
          mountPath: /etc/trino/catalog
        - name: hadoop-config
          mountPath: /etc/hadoop
        - name: data
          mountPath: /data/trino
        resources:
          {{ toYaml .Values.trino.coordinator.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /v1/info
            port: http
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /v1/info
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: config
        configMap:
          name: {{ include "trino.name" . }}-coordinator
          items:
          - key: node.properties
            path: node.properties
          - key: jvm.config
            path: jvm.config
          - key: config.properties
            path: config.properties
          - key: log.properties
            path: log.properties
      - name: catalog
        configMap:
          name: {{ include "trino.name" . }}-catalog
      - name: hadoop-config
        configMap:
          name: {{ include "trino.name" . }}-coordinator
          items:
          - key: core-site.xml
            path: core-site.xml
          - key: hdfs-site.xml
            path: hdfs-site.xml
      - name: data
        emptyDir: {}