apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml -o ./kompose/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: worker02
  name: worker02
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8081
  selector:
    io.kompose.service: worker02
