global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'data-cluster'
    environment: 'development'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'node-exporter'
    static_configs:
      - targets: [ 'node-exporter:9100' ]
        labels:
          service: 'node-exporter'

  - job_name: kafka
    static_configs:
      - targets: [ 'kafka-exporter:9308' ]
        labels:
          service: 'kafka'

  - job_name: clickhouse
    static_configs:
      - targets: [ 'clickhouse-exporter:9116' ]
        labels:
          service: 'clickhouse'