apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse.name" . }}
  labels:
      {{ include "clickhouse.labels" . | nindent 4 }}
spec:
  type: {{ .Values.clickhouse.service.type }}
  ports:
    - port: {{ .Values.clickhouse.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.clickhouse.service.tcpPort }}
      targetPort: native
      protocol: TCP
      name: native
    - port: {{ .Values.clickhouse.service.interserverPort }}
      targetPort: interserver
      protocol: TCP
      name: interserver
  selector:
    {{ include "clickhouse.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse.name" . }}-headless
  labels:
    {{ include "clickhouse.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.clickhouse.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.clickhouse.service.tcpPort }}
      targetPort: native
      protocol: TCP
      name: native
    - port: {{ .Values.clickhouse.service.interserverPort }}
      targetPort: interserver
      protocol: TCP
      name: interserver
  selector:
    {{ include "clickhouse.selectorLabels" . | nindent 4 }}