superset:
  replicas: 1

  image:
    repository: apache/superset
    tag: "3.0.2"
    pullPolicy: IfNotPresent

  nameOverride: ""
  fullnameOverride: ""

  service:
    type: ClusterIP
    port: 8088

  ingress:
    enabled: false
    className: ""
    annotations: { }
    hosts:
      - host: superset.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: [ ]

  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

  env:
    secretKey: "your_secret_key_here"

    auth:
      username: admin
      password: password

    database:
      type: postgres
      host: ""
      port: 5432
      name: superset
      username: superset
      password: superset

    redis:
      enabled: true
      host: "redis"
      port: 6379
      password: redispassword

    clickhouse:
      enabled: true
      host: clickhouse
      port: 8123
      database: ecommerce
      username: admin
      password: password
      protocol: http
