apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "trino.name" . }}-worker
  labels:
    {{ include "trino.labels" . | nindent 4 }}
    component: worker
data:
  node.properties: |
    node.environment=production
    node.data-dir=/data/trino
    plugin.dir=/usr/lib/trino/plugin

  jvm.config: |
    -server
    -Xmx{{ .Values.trino.worker.jvm.maxHeapSize }}
    -XX:+{{ .Values.trino.worker.jvm.gcMethod.type }}
    -XX:G1HeapRegionSize={{ .Values.trino.worker.jvm.gcMethod.g1.heapRegionSize }}
    -XX:+UseGCOverheadLimit
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:+ExitOnOutOfMemoryError
    -Djdk.attach.allowAttachSelf=true
    -Djdk.nio.maxCachedBufferSize=2000000

  config.properties: |
    coordinator=false
    http-server.http.port=8080
    discovery.uri=http://{{ include "trino.name" . }}-coordinator:8080
    query.max-memory=2GB
    query.max-memory-per-node=1GB
    memory.heap-headroom-per-node=512MB

  log.properties: |
    io.trino=INFO

  core-site.xml: |
    <?xml version="1.0"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration>
      <property>
        <name>fs.defaultFS</name>
        <value>hdfs://{{ .Values.trino.hdfs.namenode.host }}:{{ .Values.trino.hdfs.namenode.rpcPort }}</value>
      </property>
      <property>
        <name>hadoop.http.staticuser.user</name>
        <value>root</value>
      </property>
    </configuration>

  hdfs-site.xml: |
    <?xml version="1.0"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration>
      <property>
        <name>dfs.replication</name>
        <value>{{ .Values.trino.hdfs.replication }}</value>
      </property>
      <property>
        <name>dfs.webhdfs.enabled</name>
        <value>true</value>
      </property>
      <property>
        <name>dfs.permissions.enabled</name>
        <value>false</value>
      </property>
      <property>
        <name>dfs.namenode.datanode.registration.ip-hostname-check</name>
        <value>false</value>
      </property>
    </configuration>