apiVersion: v1
kind: Service
metadata:
  name: {{ include "trino.name" . }}-worker
  labels:
    {{ include "trino.labels" . | nindent 4 }}
    component: worker
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{ include "trino.selectorLabels" . | nindent 4 }}
    component: worker