apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis.name" . }}-config
  labels:
    {{ include "redis.labels" . | nindent 4 }}
data:
  redis.conf: |
    maxmemory {{ .Values.redis.config.maxmemory }}
    maxmemory-policy {{ .Values.redis.config.maxmemoryPolicy }}
    save ""
    appendonly no